services:
  backend:
    build: ./crud_app
    restart: always
    ports:
      - 8000:8000
    networks:
      - crud-postgres
    environment:
      db_address: db
      db_username: postgres
      db_name: postgres
      db_password: ${DB_PASSWORD}

  db:
    image: postgres:16
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - crud-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    expose:
      - 5432

volumes:
  db-data:

networks:
  crud-postgres:
