apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv
  namespace: crud-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  hostPath:
    path: "/mnt/data/postgres"